
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Josephomololu98$
#    url: jdbc:mysql://localhost:3306/triviaQuestions
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Josephomololu98$
    url: jdbc:mysql://localhost:3306/triviaQuestions
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false