package dev.iyanuoluwa.triviaquestions.repository;

public interface MYSQLQueries {
 String RANDOMISE_QUIZ = "SELECT * FROM TRIVIA_QUESTION" +
            " WHERE " +
            " CATEGORY = ?1 AND DIFFICULTY =?2 " +
           " ORDER BY RAND()";
   String QUESTIONS_BY_CATEGORY = "SELECT CATEGORY, COUNT(QUESTION) AS QUESTIONS_PER_CATEGORY FROM TRIVIA_QUESTION GROUP BY CATEGORY";

   String DIFFICULTY_BY_CATEGORY = "SELECT CATEGORY, DIFFICULTY, COUNT(DIFFICULTY) AS QUESTIONS_PER_CATEGORY_DIFFICULTY " +
           "FROM TRIVIA_QUESTION GROUP BY CATEGORY, DIFFICULTY ORDER BY CATEGORY ASC, FIELD(DIFFICULTY, 'EASY','MEDIUM','HARD')";

   String FIND_BY_TWO_CATEGORY ="SELECT * FROM TRIVIA_QUESTION" +
           " WHERE " +
           " CATEGORY IN (?1,?2)";

}
